name: sync_ops
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8          # Icons cho giao diện iOS style
  flutter_bloc: ^9.1.0             # Thư viện quản lý state dựa trên BLoC pattern
  freezed_annotation: ^3.0.0       # Annotations cho freezed code generation
  json_annotation: ^4.9.0          # Annotations cho JSON serialization
  json_serializable: ^6.9.4        # Code generation cho JSON serialization
  cached_network_image: ^3.4.1     # Tải và cache hình ảnh từ mạng
  path_provider: ^2.1.5            # Truy cập đường dẫn hệ thống tệp
  carousel_slider: ^5.0.0          # Widget hiển thị carousel/slider
  http: ^1.3.0                     # Thực hiện HTTP requests
  get_it: ^8.0.3                   # Service locator cho dependency injection
  injectable: ^2.5.0               # Tạo code tự động cho dependency injection
  shared_preferences: ^2.5.2       # Lưu trữ dữ liệu đơn giản dạng key-value
  hive_ce: ^2.10.1                 # Lightweight database NoSQL (phiên bản community edition)
  hive_ce_flutter: ^2.2.0          # Flutter extensions cho Hive CE
  go_router: ^14.8.1               # Routing và navigation
  flutter_svg: ^2.0.17             # Hiển thị SVG files
  shimmer: ^3.0.0                  # Hiệu ứng loading shimmer        
  equatable: ^2.0.7
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.7.1
  mobile_scanner: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4                  # Code generation cho immutable classes
  build_runner: ^2.4.15            # Tool chạy code generators
  flutter_lints: ^5.0.0            # Linting rules cho Flutter
  injectable_generator: ^2.7.0     # Code generation cho injectable
  hive_ce_generator: ^1.8.2        # Code generation cho Hive CE
  mockito: ^5.4.5                  # Framework cho unit testing với mocks

flutter:                           # Cấu hình Flutter
  uses-material-design: true       # Sử dụng Material Design
  generate: true                   # Cho phép code generation cho localization

  assets:                          # Khai báo assets được sử dụng trong ứng dụng
    - assets/images/               # Thư mục chứa hình ảnh

# Thêm cấu hình l10n
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

  # flutter pub run build_runner build --delete-conflicting-outputs  # Lệnh để chạy code generation